# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77ee3a9e193cd31205b3c1af2d2a407d8e5c8c8338b005850fdecff5f927907c4ce8a02cc5d1fc3e7af3a2ea1a100cc96eb84f5326cc9d8ea1f48cb0c76bd3dd
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>

test:
  secret_key_base: 257257f3058dbdebd1315dcccab895fdfb7b4b3b21909145047ad994dc0632b4fe6da7321cbcb23f64498950d05c5d1e7143e286f5aa12b1bdd9cb888ca33c25
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
